title: Website for My Python Portfolio
description: A collection of 7 Python exercises published using GitHub Pages and Jekyll Cayman Theme.

url: "https://canankilic.github.io"
baseurl: "/github_website/assignment2"

remote_theme: pages-themes/cayman

markdown: kramdown
plugins:
  - jekyll-remote-theme

header_pages:
  - exercise1.md
  - exercise2.md
  - exercise3.md
  - bma.md
  - calculator.md
  - calender.md
  - hello.md

