title: Website for My Python Portfolio
description: A collection of 7 Python exercises published using GitHub Pages and Jekyll Hacker Theme.

url: "https://canankilic.github.io"
baseurl: "/github_website"

remote_theme: pages-themes/modernist

markdown: kramdown
plugins:
  - jekyll-remote-theme

header_pages:
  - exercise1.md
  - exercise2.md
  - exercise3.md
  - bma.md
  - calculator.md
  - calender.md
  - hello.md

theme_settings:
accent_color: "#00FF99"
header_background: "#000000"
link_color: "#00FFAA"
