theme: jekyll-theme-cayman

title: Website for My Python Portfolio - Canan Kilic 80307
description: A collection of 7 Python exercises published using GitHub Pages and Jekyll Cayman Theme.

baseurl: ""
url: ""

markdown: kramdown
