title: Website for My Python Portfolio - Canan Kilic
description: A collection of Python exercises, a presentation for Assignment 2 and pipeline for Assignment 3.
remote_theme: pages-themes/cayman

baseurl: "/github_website"
url: "https://canankilic.github.io"
