title: Website for My Python Portfolio
description: A collection of Python exercises published using GitHub Pages.
remote_theme: pages-themes/cayman

baseurl: "/github_website"
url: "https://canankilic.github.io"

exclude:
  - assignment1/

header_pages:
  - exercise1.md
  - exercise2.md
  - exercise3.md
  - bma.md
  - calculator.md
  - calender.md
  - hello.md
