title: Website for My Python Portfolio Canan Kilic 80307
description: A collection of Python exercises published using GitHub Pages. Assignments 2 and 3 include a Jekyll presentation and the Jekyll Cayman theme.

url: "https://canankilic.github.io"
baseurl: "/github_website/assignment2"

theme: jekyll-theme-cayman

markdown: kramdown

header_pages:
  - exercise1.md
  - exercise2.md
  - exercise3.md
  - bma.md
  - calculator.md
  - calender.md
  - hello.md
