remote_theme: pages-themes/cayman
title: Website for My Python Portfolio
description: A collection of 7 Python exercises.

baseurl: ""
url: ""

include:
  - exercise1.md
  - exercise2.md
  - exercise3.md
  - bma.md
  - calculator.md
  - calender.md
  - hello.md
